name: vShop
main: me.arifBanai.vShop.Main
author: smeef
website: https://github.com/arif-banai
version: 3.0
description: A virtual shop, great for economy servers
depend: [Vault,IDLogger]
database: true
api-version: 1.13
commands:
  buy:
    description: Buy an item from the shop
    permission: vshop.commands.buy
  sell:
    description: Put an item up for sale
    permission: vshop.commands.sell
  recall:
    description: Recall an item from the shop
    permission: vshop.commands.recall
  find:
    description: Find players selling this item
    permission: vshop.commands.find
  stock:
    description: Browse through a player's wares
    permission: vshop.commands.stock
  test:
    description: Test command for debugging
    permission: vshop.commands.test
permissions:
  vshop.commands.*:
    description: Access to all vShop commands
    children:
      vshop.commands.buy: true
      vshop.commands.sell: true
      vshop.commands.recall: true
      vshop.commands.find: true
      vshop.commands.stock: true
  vshop.commands.buy: 
    description: Permission to use /buy
    default: op
  vshop.commands.sell: 
    description: Permission to use /sell
    default: op
  vshop.commands.recall: 
    description: Permission to use /buy
    default: op
  vshop.commands.find: 
    description: Permission to use /buy
    default: op
  vshop.commands.stock: 
    description: Permission to use /buy
    default: op
  vshop.commands.test: 
    description: Permission to use /test
    default: op