broadcast-offers: true
log-transactions: false
using-sqlite: true
db:
  host: localhost
  port: 3306
  schema: minecraft
  username: root
  password: password
  dialect: mysql
# Valid dialects:
# mysql