#redis would be useful if your server is huge and have many concurrent players
broadcast-offers: true
log-transactions: false
using-webapp: false
using-redis: false
using-sqlite: true
db:
  host: localhost
  port: 3306
  schema: minecraft
  username: root
  password: password
  dialect: mysql
# Valid dialects:
# mysql