name: vShop
main: main.java.arifbanai.vShop.Main
author: smeef
website: https://github.com/arif-banai
version: 3.0
description: A virtual shop, great for economy servers
depend: [Vault,IDLogger]
database: true
api-version: 1.13
commands:
  buy:
    description: "Buy items: <amount> <itemName> <maxPricePerItem>"
    permission: vshop.commands.buy
  sell:
    description: "Sell items: <amount> <itemName> <pricePerItem>"
    permission: vshop.commands.sell
  recall:
    description: "Recall an offer for some item: <itemName>"
    permission: vshop.commands.recall
  find:
    description: "Find offers for some item: <itemName> [pageNumber]"
    permission: vshop.commands.find
  stock:
    description: "Find offers by some player: <playerName> [pageNumber]"
    permission: vshop.commands.stock
  sales:
    description: "Get your sales history: [pageNumber]"
    permission: vshop.commands.sales
permissions:
  vshop.commands.*:
    description: Access to all vShop commands
    children:
      vshop.commands.buy: true
      vshop.commands.sell: true
      vshop.commands.recall: true
      vshop.commands.find: true
      vshop.commands.stock: true
      vshop.commands.sales: true
  vshop.commands.buy: 
    description: Permission to use /buy
    default: op
  vshop.commands.sell: 
    description: Permission to use /sell
    default: op
  vshop.commands.recall: 
    description: Permission to use /buy
    default: op
  vshop.commands.find: 
    description: Permission to use /buy
    default: op
  vshop.commands.stock: 
    description: Permission to use /buy
    default: op
  vshop.commands.sales: 
    description: Permission to use /sales
    default: op